# Generated by Django 3.1.7 on 2021-04-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_auto_20210402_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessagesFromSpace',
            new_name='MessageFromSpace',
        ),
    ]
